// Code generated by danmuji — DO NOT EDIT.

package ferrouswheel_test

import (
	"strings"
	"testing"

	ferrouswheel "github.com/odvcencio/ferrous-wheel"
	"github.com/stretchr/testify/assert"

	// =============================================================================
	// TYPE SYSTEM
	// =============================================================================
	"github.com/stretchr/testify/require"
)

func TestTranspileEnum(t *testing.T) {
	t.Run("a simple enum declaration", func(t *testing.T) {
		source := []byte("package main\nenum Color {\n\tRed,\n\tGreen,\n\tBlue(int),\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:20: given a simple enum declaration > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates struct with tag field", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "type Color struct"), "danmuji:23: given a simple enum declaration > then generates struct with tag field | expect (expect strings.Contains(goCode, \"type Color struct\"))")
			assert.True(t, strings.Contains(goCode, "tag int"), "danmuji:24: given a simple enum declaration > then generates struct with tag field | expect (expect strings.Contains(goCode, \"tag int\"))")
		})
		t.Run("generates variant constants", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "ColorRed = 0"), "danmuji:27: given a simple enum declaration > then generates variant constants | expect (expect strings.Contains(goCode, \"ColorRed = 0\"))")
			assert.True(t, strings.Contains(goCode, "ColorGreen = 1"), "danmuji:28: given a simple enum declaration > then generates variant constants | expect (expect strings.Contains(goCode, \"ColorGreen = 1\"))")
			assert.True(t, strings.Contains(goCode, "ColorBlue = 2"), "danmuji:29: given a simple enum declaration > then generates variant constants | expect (expect strings.Contains(goCode, \"ColorBlue = 2\"))")
		})
		t.Run("generates constructor functions", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func Red() Color"), "danmuji:32: given a simple enum declaration > then generates constructor functions | expect (expect strings.Contains(goCode, \"func Red() Color\"))")
			assert.True(t, strings.Contains(goCode, "func Green() Color"), "danmuji:33: given a simple enum declaration > then generates constructor functions | expect (expect strings.Contains(goCode, \"func Green() Color\"))")
			assert.True(t, strings.Contains(goCode, "func Blue(v0 int) Color"), "danmuji:34: given a simple enum declaration > then generates constructor functions | expect (expect strings.Contains(goCode, \"func Blue(v0 int) Color\"))")
		})
		t.Run("eliminates enum keyword", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "enum "), "danmuji:37: given a simple enum declaration > then eliminates enum keyword | reject (reject strings.Contains(goCode, \"enum \"))")
		})
	})
}

func TestTranspileDerive(t *testing.T) {
	t.Run("derive Stringer for a type", func(t *testing.T) {
		source := []byte("package main\nderive Stringer for Color\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:48: given derive Stringer for a type > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates String method", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (x Color) String() string"), "danmuji:51: given derive Stringer for a type > then generates String method | expect (expect strings.Contains(goCode, \"func (x Color) String() string\"))")
		})
		t.Run("eliminates derive keyword", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "derive"), "danmuji:54: given derive Stringer for a type > then eliminates derive keyword | reject (reject strings.Contains(goCode, \"derive\"))")
		})
	})
	t.Run("derive Equal for a type", func(t *testing.T) {
		source := []byte("package main\nderive Equal for Point\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:63: given derive Equal for a type > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates Equal method with correct signature", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (x Point) Equal(other Point) bool"), "danmuji:66: given derive Equal for a type > then generates Equal method with correct signature | expect (expect strings.Contains(goCode, \"func (x Point) Equal(other Point) bool\"))")
			assert.True(t, strings.Contains(goCode, "return x == other"), "danmuji:67: given derive Equal for a type > then generates Equal method with correct signature | expect (expect strings.Contains(goCode, \"return x == other\"))")
		})
	})
	t.Run("derive JSON for a type", func(t *testing.T) {
		source := []byte("package main\nderive JSON for Config\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:76: given derive JSON for a type > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates MarshalJSON method", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (x Config) MarshalJSON() ([]byte, error)"), "danmuji:79: given derive JSON for a type > then generates MarshalJSON method | expect (expect strings.Contains(goCode, \"func (x Config) MarshalJSON() ([]byte, error)\"))")
			assert.True(t, strings.Contains(goCode, "json.Marshal"), "danmuji:80: given derive JSON for a type > then generates MarshalJSON method | expect (expect strings.Contains(goCode, \"json.Marshal\"))")
			assert.True(t, strings.Contains(goCode, "func (x *Config) UnmarshalJSON(data []byte) error"), "danmuji:81: given derive JSON for a type > then generates UnmarshalJSON method | expect (expect strings.Contains(goCode, \"func (x *Config) UnmarshalJSON(data []byte) error\"))")
			assert.True(t, strings.Contains(goCode, "json.Unmarshal"), "danmuji:82: given derive JSON for a type > then generates UnmarshalJSON method | expect (expect strings.Contains(goCode, \"json.Unmarshal\"))")
		})
		t.Run("injects encoding/json import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"encoding/json\""), "danmuji:83: given derive JSON for a type > then injects encoding/json import | expect (expect strings.Contains(goCode, \"\\\"encoding/json\\\"\"))")
		})
	})
}

func TestTranspileImpl(t *testing.T) {
	t.Run("an impl block with methods", func(t *testing.T) {
		source := []byte("package main\nimpl Point {\n\tfunc Area() int {\n\t\treturn 0\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:94: given an impl block with methods > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("adds receiver to methods", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (self Point)"), "danmuji:97: given an impl block with methods > then adds receiver to methods | expect (expect strings.Contains(goCode, \"func (self Point)\"))")
		})
		t.Run("eliminates impl keyword", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "impl "), "danmuji:100: given an impl block with methods > then eliminates impl keyword | reject (reject strings.Contains(goCode, \"impl \"))")
		})
	})
}

// =============================================================================
// BINDINGS
// =============================================================================

func TestTranspileLet(t *testing.T) {
	t.Run("a let declaration", func(t *testing.T) {
		source := []byte("package main\nfunc main() {\n\tlet x = 42\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:115: given a let declaration > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to short variable declaration", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "x := 42"), "danmuji:118: given a let declaration > then converts to short variable declaration | expect (expect strings.Contains(goCode, \"x := 42\"))")
		})
		t.Run("eliminates let keyword", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "let "), "danmuji:121: given a let declaration > then eliminates let keyword | reject (reject strings.Contains(goCode, \"let \"))")
		})
	})
	t.Run("a let multi declaration", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tlet (a, b) = getPair()\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:130: given a let multi declaration > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to multi-assignment", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "a, b := getPair()"), "danmuji:133: given a let multi declaration > then converts to multi-assignment | expect (expect strings.Contains(goCode, \"a, b := getPair()\"))")
		})
	})
}

func TestTranspileLambda(t *testing.T) {
	t.Run("a lambda expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tdouble := fn(x) x * 2\n\t_ = double\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:144: given a lambda expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates func literal with interface params", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func(x interface{}) interface{}"), "danmuji:147: given a lambda expression > then generates func literal with interface params | expect (expect strings.Contains(goCode, \"func(x interface{}) interface{}\"))")
		})
		t.Run("captures full body expression", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "return x * 2"), "danmuji:150: given a lambda expression > then captures full body expression | expect (expect strings.Contains(goCode, \"return x * 2\"))")
		})
	})
}

// =============================================================================
// EXPRESSIONS
// =============================================================================

func TestTranspileTernary(t *testing.T) {
	t.Run("a ternary expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := true ? 1 : 0\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:165: given a ternary expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("wraps in IIFE", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "interface{}"), "output should not contain interface{}")
			assert.True(t, strings.Contains(goCode, "func()"), "danmuji:168: given a ternary expression > then wraps in IIFE | expect func() wrapper")
		})
		t.Run("includes condition", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if true"), "danmuji:171: given a ternary expression > then includes condition | expect (expect strings.Contains(goCode, \"if true\"))")
		})
		t.Run("includes both branches", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "return 1"), "danmuji:174: given a ternary expression > then includes both branches | expect (expect strings.Contains(goCode, \"return 1\"))")
			assert.True(t, strings.Contains(goCode, "return 0"), "danmuji:175: given a ternary expression > then includes both branches | expect (expect strings.Contains(goCode, \"return 0\"))")
		})
	})
}

func TestTranspileNullCoalesce(t *testing.T) {
	t.Run("a null coalesce expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := val ?? \"default\"\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:186: given a null coalesce expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("uses reflect for zero check", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "reflect.ValueOf"), "danmuji:189: given a null coalesce expression > then uses reflect for zero check | expect (expect strings.Contains(goCode, \"reflect.ValueOf\"))")
			assert.True(t, strings.Contains(goCode, "IsZero"), "danmuji:190: given a null coalesce expression > then uses reflect for zero check | expect (expect strings.Contains(goCode, \"IsZero\"))")
		})
		t.Run("injects reflect import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"reflect\""), "danmuji:193: given a null coalesce expression > then injects reflect import | expect (expect strings.Contains(goCode, \"\\\"reflect\\\"\"))")
		})
	})
}

func TestTranspileSafeNavigation(t *testing.T) {
	t.Run("a safe navigation expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := obj?.name\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:204: given a safe navigation expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("uses reflect for field access", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "reflect.ValueOf"), "danmuji:207: given a safe navigation expression > then uses reflect for field access | expect (expect strings.Contains(goCode, \"reflect.ValueOf\"))")
			assert.True(t, strings.Contains(goCode, "FieldByName"), "danmuji:208: given a safe navigation expression > then uses reflect for field access | expect (expect strings.Contains(goCode, \"FieldByName\"))")
		})
		t.Run("checks for nil", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "IsNil()"), "danmuji:211: given a safe navigation expression > then checks for nil | expect (expect strings.Contains(goCode, \"IsNil()\"))")
		})
	})
}

func TestTranspileErrorPropagation(t *testing.T) {
	t.Run("a try expression", func(t *testing.T) {
		source := []byte("package main\nfunc doSomething() (string, error) { return \"ok\", nil }\nfunc f() (string, error) {\n\tx := try doSomething()\n\treturn x, nil\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:222: given a try expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates propagation assignment", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "x, _fwTryErr0 := doSomething()"), "danmuji:225: given a try expression > then rewrites into a checked assignment | expect (expect strings.Contains(goCode, \"x, _fwTryErr0 := doSomething()\"))")
			assert.True(t, strings.Contains(goCode, "return *new(string), _fwTryErr0"), "danmuji:226: given a try expression > then propagates using the enclosing function signature | expect (expect strings.Contains(goCode, \"return *new(string), _fwTryErr0\"))")
		})
	})
}

func TestTranspilePipeline(t *testing.T) {
	t.Run("a pipeline expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := data |> transform\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:237: given a pipeline expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to function application", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "transform(data)"), "danmuji:240: given a pipeline expression > then converts to function application | expect (expect strings.Contains(goCode, \"transform(data)\"))")
		})
		t.Run("eliminates pipe operator", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "|>"), "danmuji:243: given a pipeline expression > then eliminates pipe operator | reject (reject strings.Contains(goCode, \"|>\"))")
		})
	})
}

func TestTranspileFString(t *testing.T) {
	t.Run("an f-string with interpolation", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := f\"hello {name}\"\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:254: given an f-string with interpolation > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to fmt.Sprintf", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "fmt.Sprintf"), "danmuji:257: given an f-string with interpolation > then converts to fmt.Sprintf | expect (expect strings.Contains(goCode, \"fmt.Sprintf\"))")
			assert.True(t, strings.Contains(goCode, "hello %v"), "danmuji:258: given an f-string with interpolation > then converts to fmt.Sprintf | expect (expect strings.Contains(goCode, \"hello %v\"))")
		})
		t.Run("injects fmt import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"fmt\""), "danmuji:261: given an f-string with interpolation > then injects fmt import | expect (expect strings.Contains(goCode, \"\\\"fmt\\\"\"))")
		})
	})
	t.Run("an f-string without interpolation", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := f\"hello\"\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:270: given an f-string without interpolation > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("becomes a regular string", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"hello\""), "danmuji:273: given an f-string without interpolation > then becomes a regular string | expect (expect strings.Contains(goCode, \"\\\"hello\\\"\"))")
			assert.False(t, strings.Contains(goCode, "Sprintf"), "danmuji:274: given an f-string without interpolation > then becomes a regular string | reject (reject strings.Contains(goCode, \"Sprintf\"))")
		})
	})
}

func TestTranspileListComprehension(t *testing.T) {
	t.Run("a list comprehension without filter", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := [x for x in items]\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:285: given a list comprehension without filter > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates IIFE returning slice", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func() []interface{}"), "danmuji:288: given a list comprehension without filter > then generates IIFE returning slice | expect (expect strings.Contains(goCode, \"func() []interface{}\"))")
		})
		t.Run("ranges over iterable", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "range items"), "danmuji:291: given a list comprehension without filter > then ranges over iterable | expect (expect strings.Contains(goCode, \"range items\"))")
		})
	})
	t.Run("a list comprehension with filter", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := [x for x in items if x > 0]\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:300: given a list comprehension with filter > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("includes filter condition", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if x > 0"), "danmuji:303: given a list comprehension with filter > then includes filter condition | expect (expect strings.Contains(goCode, \"if x > 0\"))")
		})
	})
}

func TestTranspileMatch(t *testing.T) {
	t.Run("a match expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := match val {\n\t\t1 => \"one\",\n\t\t2 => \"two\",\n\t}\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:314: given a match expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates switch in IIFE", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "switch val"), "danmuji:317: given a match expression > then generates switch in IIFE | expect (expect strings.Contains(goCode, \"switch val\"))")
		})
		t.Run("has exhaustive default panic", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "panic("), "danmuji:320: given a match expression > then has exhaustive default panic | expect (expect strings.Contains(goCode, \"panic(\"))")
			assert.True(t, strings.Contains(goCode, "non-exhaustive match"), "danmuji:321: given a match expression > then has exhaustive default panic | expect (expect strings.Contains(goCode, \"non-exhaustive match\"))")
		})
	})
	t.Run("a match with guard clause", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := match val {\n\t\t1 if val > 0 => \"positive one\",\n\t\t0 => \"zero\",\n\t}\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:330: given a match with guard clause > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("includes guard clause", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if val > 0"), "danmuji:333: given a match with guard clause > then includes guard clause | expect (expect strings.Contains(goCode, \"if val > 0\"))")
		})
	})
}

// =============================================================================
// CONTROL FLOW
// =============================================================================

func TestTranspileForIn(t *testing.T) {
	t.Run("for-in over a slice", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tfor v in items {\n\t\t_ = v\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:348: given for-in over a slice > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to range loop", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "for _, v := range items"), "danmuji:351: given for-in over a slice > then converts to range loop | expect (expect strings.Contains(goCode, \"for _, v := range items\"))")
		})
	})
	t.Run("for-in over a range expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tfor i in 0 .. 10 {\n\t\t_ = i\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:360: given for-in over a range expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to C-style for loop", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "for i := 0; i < 10; i++"), "danmuji:363: given for-in over a range expression > then converts to C-style for loop | expect (expect strings.Contains(goCode, \"for i := 0; i < 10; i++\"))")
		})
	})
	t.Run("for-in with index", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tfor i, v in items {\n\t\t_ = i\n\t\t_ = v\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:372: given for-in with index > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("preserves both index and value", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "for i, v := range items"), "danmuji:375: given for-in with index > then preserves both index and value | expect (expect strings.Contains(goCode, \"for i, v := range items\"))")
		})
	})
}

func TestTranspileGuard(t *testing.T) {
	t.Run("a guard statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tguard x > 0 else {\n\t\treturn\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:386: given a guard statement > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("negates the condition", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if !(x > 0)"), "danmuji:389: given a guard statement > then negates the condition | expect (expect strings.Contains(goCode, \"if !(x > 0)\"))")
		})
		t.Run("eliminates guard keyword", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "guard "), "danmuji:392: given a guard statement > then eliminates guard keyword | reject (reject strings.Contains(goCode, \"guard \"))")
		})
	})
}

func TestTranspileControlSugar(t *testing.T) {
	t.Run("an unless statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tunless x > 0 {\n\t\treturn\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles to negated if", func(t *testing.T) {
			require.NoError(t, err, "danmuji:403: given an unless statement > then transpiles to negated if | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "if !(x > 0)"), "danmuji:404: given an unless statement > then transpiles to negated if | expect (expect strings.Contains(goCode, \"if !(x > 0)\"))")
		})
	})
	t.Run("an until statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tuntil x > 10 {\n\t\tx = x + 1\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles to negated for", func(t *testing.T) {
			require.NoError(t, err, "danmuji:413: given an until statement > then transpiles to negated for | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "for !(x > 10)"), "danmuji:414: given an until statement > then transpiles to negated for | expect (expect strings.Contains(goCode, \"for !(x > 10)\"))")
		})
	})
	t.Run("a repeat statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\trepeat 5 {\n\t\tfmt.Println(\"hi\")\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles to counted for loop", func(t *testing.T) {
			require.NoError(t, err, "danmuji:423: given a repeat statement > then transpiles to counted for loop | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "for _i := 0; _i < 5; _i++"), "danmuji:424: given a repeat statement > then transpiles to counted for loop | expect (expect strings.Contains(goCode, \"for _i := 0; _i < 5; _i++\"))")
		})
	})
	t.Run("a swap statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tswap(a, b)\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles to tuple swap", func(t *testing.T) {
			require.NoError(t, err, "danmuji:433: given a swap statement > then transpiles to tuple swap | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "a, b = b, a"), "danmuji:434: given a swap statement > then transpiles to tuple swap | expect (expect strings.Contains(goCode, \"a, b = b, a\"))")
		})
	})
}

func TestTranspileDeferError(t *testing.T) {
	t.Run("a defer! statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tdefer! f.Close()\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:445: given a defer! statement > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("wraps in error-capturing defer", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "defer func()"), "danmuji:448: given a defer! statement > then wraps in error-capturing defer | expect (expect strings.Contains(goCode, \"defer func()\"))")
			assert.True(t, strings.Contains(goCode, "_cerr"), "danmuji:449: given a defer! statement > then wraps in error-capturing defer | expect (expect strings.Contains(goCode, \"_cerr\"))")
			assert.True(t, strings.Contains(goCode, "f.Close()"), "danmuji:450: given a defer! statement > then wraps in error-capturing defer | expect (expect strings.Contains(goCode, \"f.Close()\"))")
		})
	})
}

func TestTranspileIfLet(t *testing.T) {
	t.Run("an if-let statement", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tif let x = getValue() {\n\t\t_ = x\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:461: given an if-let statement > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("converts to init-if with nil check", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if x := getValue(); x != nil"), "danmuji:464: given an if-let statement > then converts to init-if with nil check | expect (expect strings.Contains(goCode, \"if x := getValue(); x != nil\"))")
		})
	})
	t.Run("an if-let with else", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tif let x = getValue() {\n\t\t_ = x\n\t} else {\n\t\tpanic(\"nil\")\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:473: given an if-let with else > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("includes else block", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "else"), "danmuji:476: given an if-let with else > then includes else block | expect (expect strings.Contains(goCode, \"else\"))")
		})
	})
}

// =============================================================================
// GENERIC TYPES
// =============================================================================

func TestTranspileResultType(t *testing.T) {
	t.Run("code using Result[T]", func(t *testing.T) {
		source := []byte("package main\nfunc divide(a, b int) Result[int] {\n\treturn Ok[int](a / b)\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:491: given code using Result[T] > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("injects Result type definition", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "type Result[T any] struct"), "danmuji:494: given code using Result[T] > then injects Result type definition | expect (expect strings.Contains(goCode, \"type Result[T any] struct\"))")
		})
		t.Run("injects Ok and Err constructors", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func Ok[T any]"), "danmuji:497: given code using Result[T] > then injects Ok and Err constructors | expect (expect strings.Contains(goCode, \"func Ok[T any]\"))")
			assert.True(t, strings.Contains(goCode, "func Err[T any]"), "danmuji:498: given code using Result[T] > then injects Ok and Err constructors | expect (expect strings.Contains(goCode, \"func Err[T any]\"))")
		})
		t.Run("injects Unwrap method", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (r Result[T]) Unwrap()"), "danmuji:501: given code using Result[T] > then injects Unwrap method | expect (expect strings.Contains(goCode, \"func (r Result[T]) Unwrap()\"))")
		})
	})
}

func TestTranspileOptionType(t *testing.T) {
	t.Run("code using Option[T]", func(t *testing.T) {
		source := []byte("package main\nfunc find(id int) Option[string] {\n\treturn Some[string](\"alice\")\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:512: given code using Option[T] > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("injects Option type definition", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "type Option[T any] struct"), "danmuji:515: given code using Option[T] > then injects Option type definition | expect (expect strings.Contains(goCode, \"type Option[T any] struct\"))")
		})
		t.Run("injects Some and None constructors", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func Some[T any]"), "danmuji:518: given code using Option[T] > then injects Some and None constructors | expect (expect strings.Contains(goCode, \"func Some[T any]\"))")
			assert.True(t, strings.Contains(goCode, "func None[T any]"), "danmuji:519: given code using Option[T] > then injects Some and None constructors | expect (expect strings.Contains(goCode, \"func None[T any]\"))")
		})
	})
}

func TestTranspileNoGenericTypesWhenUnused(t *testing.T) {
	t.Run("code that does not use Result or Option", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tlet x = 42\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:530: given code that does not use Result or Option > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("does not inject Result", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "type Result[T any]"), "danmuji:533: given code that does not use Result or Option > then does not inject Result | reject (reject strings.Contains(goCode, \"type Result[T any]\"))")
		})
		t.Run("does not inject Option", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "type Option[T any]"), "danmuji:536: given code that does not use Result or Option > then does not inject Option | reject (reject strings.Contains(goCode, \"type Option[T any]\"))")
		})
	})
}

// =============================================================================
// LOW-LEVEL MEMORY FEATURES
// =============================================================================

func TestTranspileArena(t *testing.T) {
	t.Run("an arena block", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tarena scratch {\n\t\tx := 1\n\t\t_ = x\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:551: given an arena block > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates arena allocator", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "_arena_scratch"), "danmuji:554: given an arena block > then generates arena allocator | expect (expect strings.Contains(goCode, \"_arena_scratch\"))")
			assert.True(t, strings.Contains(goCode, "_arenaAlloc_scratch"), "danmuji:555: given an arena block > then generates arena allocator | expect (expect strings.Contains(goCode, \"_arenaAlloc_scratch\"))")
			assert.True(t, strings.Contains(goCode, "unsafe.Pointer"), "danmuji:556: given an arena block > then generates arena allocator | expect (expect strings.Contains(goCode, \"unsafe.Pointer\"))")
		})
		t.Run("injects unsafe import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"unsafe\""), "danmuji:559: given an arena block > then injects unsafe import | expect (expect strings.Contains(goCode, \"\\\"unsafe\\\"\"))")
		})
	})
	t.Run("an arena block with explicit size", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tarena scratch 2048 {\n\t\tx := 1\n\t\t_ = x\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("uses custom size", func(t *testing.T) {
			require.NoError(t, err, "danmuji:568: given an arena block with explicit size > then uses custom size | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "_arenaSize := 2048"), "danmuji:569: given an arena block with explicit size > then uses custom size | expect (expect strings.Contains(goCode, \"_arenaSize := 2048\"))")
		})
	})
}

func TestTranspilePinUnpin(t *testing.T) {
	t.Run("pin and unpin statements", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tpin data\n\tunpin data\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:580: given pin and unpin statements > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates runtime calls", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "runtime.SetFinalizer"), "danmuji:583: given pin and unpin statements > then generates runtime calls | expect (expect strings.Contains(goCode, \"runtime.SetFinalizer\"))")
			assert.True(t, strings.Contains(goCode, "runtime.KeepAlive(data)"), "danmuji:584: given pin and unpin statements > then generates runtime calls | expect (expect strings.Contains(goCode, \"runtime.KeepAlive(data)\"))")
		})
		t.Run("injects runtime import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"runtime\""), "danmuji:587: given pin and unpin statements > then injects runtime import | expect (expect strings.Contains(goCode, \"\\\"runtime\\\"\"))")
		})
	})
}

func TestTranspileUnsafeCast(t *testing.T) {
	t.Run("an unsafe cast expression", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := unsafe cast(s, int)\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:598: given an unsafe cast expression > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates helper-backed cast", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "_fwUnsafeCast[int](s)"), "danmuji:601: given an unsafe cast expression > then generates helper-backed cast | expect (expect strings.Contains(goCode, \"_fwUnsafeCast[int](s)\"))")
			assert.True(t, strings.Contains(goCode, "func _fwUnsafeCast[To any, From any]"), "danmuji:602: given an unsafe cast expression > then injects unsafe cast helper | expect (expect strings.Contains(goCode, \"func _fwUnsafeCast[To any, From any]\"))")
		})
	})
}

// =============================================================================
// CONCURRENCY FEATURES
// =============================================================================

func TestTranspileFanOut(t *testing.T) {
	t.Run("a fan out block", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tfan out workers, 10 {\n\t\tdoWork()\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:616: given a fan out block > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates WaitGroup pattern", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "sync.WaitGroup"), "danmuji:619: given a fan out block > then generates WaitGroup pattern | expect (expect strings.Contains(goCode, \"sync.WaitGroup\"))")
			assert.True(t, strings.Contains(goCode, "go func()"), "danmuji:620: given a fan out block > then generates WaitGroup pattern | expect (expect strings.Contains(goCode, \"go func()\"))")
			assert.True(t, strings.Contains(goCode, ".Wait()"), "danmuji:621: given a fan out block > then generates WaitGroup pattern | expect (expect strings.Contains(goCode, \".Wait()\"))")
		})
		t.Run("uses correct worker count", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "_wi < 10"), "danmuji:624: given a fan out block > then uses correct worker count | expect (expect strings.Contains(goCode, \"_wi < 10\"))")
		})
		t.Run("injects sync import", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "\"sync\""), "danmuji:627: given a fan out block > then injects sync import | expect (expect strings.Contains(goCode, \"\\\"sync\\\"\"))")
		})
	})
}

func TestTranspileConcurrent(t *testing.T) {
	t.Run("a concurrent block", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tconcurrent {\n\t\tfetch(\"url1\")\n\t\tfetch(\"url2\")\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:638: given a concurrent block > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("wraps each statement in goroutine", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "go func()"), "danmuji:641: given a concurrent block > then wraps each statement in goroutine | expect (expect strings.Contains(goCode, \"go func()\"))")
			assert.True(t, strings.Contains(goCode, "_wg.Wait()"), "danmuji:642: given a concurrent block > then wraps each statement in goroutine | expect (expect strings.Contains(goCode, \"_wg.Wait()\"))")
		})
	})
}

func TestTranspileThrottle(t *testing.T) {
	t.Run("a throttle block", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tthrottle 100 {\n\t\tdoWork()\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:653: given a throttle block > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates throttle helper", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, `_fwThrottleWait("throttle_`), "danmuji:656: given a throttle block > then generates throttle helper | expect (expect strings.Contains(goCode, \"_fwThrottleWait(\\\"throttle_\"))")
			assert.True(t, strings.Contains(goCode, "func _fwThrottleWait(name string, rate int, burst int)"), "danmuji:657: given a throttle block > then generates throttle helper | expect (expect strings.Contains(goCode, \"func _fwThrottleWait(name string, rate int, burst int)\"))")
		})
	})
}

func TestTranspileRetry(t *testing.T) {
	t.Run("a retry block with defaults", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tretry 3 {\n\t\tdoWork()\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:668: given a retry block with defaults > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates retry loop", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "_attempt < 3"), "danmuji:671: given a retry block with defaults > then generates retry loop | expect (expect strings.Contains(goCode, \"_attempt < 3\"))")
			assert.True(t, strings.Contains(goCode, "time.Sleep"), "danmuji:672: given a retry block with defaults > then generates retry loop | expect (expect strings.Contains(goCode, \"time.Sleep\"))")
		})
	})
	t.Run("a retry block with custom params", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tretry 5 delay 500 backoff 2 {\n\t\tdoWork()\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("uses custom delay and backoff", func(t *testing.T) {
			require.NoError(t, err, "danmuji:681: given a retry block with custom params > then uses custom delay and backoff | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "_attempt < 5"), "danmuji:682: given a retry block with custom params > then uses custom delay and backoff | expect (expect strings.Contains(goCode, \"_attempt < 5\"))")
		})
	})
}

func TestTranspileBreaker(t *testing.T) {
	t.Run("a circuit breaker block", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tbreaker \"myservice\" {\n\t\tcallService()\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:693: given a circuit breaker block > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates circuit breaker logic", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "_fwBreakerDo(\"myservice\""), "danmuji:696: given a circuit breaker block > then generates circuit breaker logic | expect (expect strings.Contains(goCode, \"_fwBreakerDo(\\\"myservice\\\"\"))")
			assert.True(t, strings.Contains(goCode, "time.Since"), "danmuji:697: given a circuit breaker block > then generates circuit breaker logic | expect (expect strings.Contains(goCode, \"time.Since\"))")
		})
	})
}

// =============================================================================
// IMPORT INJECTION
// =============================================================================

func TestTranspileImportInjection(t *testing.T) {
	t.Run("code that needs reflect", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := val ?? \"default\"\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("auto-injects reflect", func(t *testing.T) {
			require.NoError(t, err, "danmuji:712: given code that needs reflect > then auto-injects reflect | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "\"reflect\""), "danmuji:713: given code that needs reflect > then auto-injects reflect | expect (expect strings.Contains(goCode, \"\\\"reflect\\\"\"))")
		})
	})
	t.Run("code that needs fmt", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tx := match val {\n\t\t1 => \"one\",\n\t}\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("auto-injects fmt", func(t *testing.T) {
			require.NoError(t, err, "danmuji:722: given code that needs fmt > then auto-injects fmt | expect (expect err == nil)")
			assert.True(t, strings.Contains(goCode, "\"fmt\""), "danmuji:723: given code that needs fmt > then auto-injects fmt | expect (expect strings.Contains(goCode, \"\\\"fmt\\\"\"))")
		})
	})
	t.Run("code that needs no extra imports", func(t *testing.T) {
		source := []byte("package main\nfunc f() {\n\tlet x = 42\n\t_ = x\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("injects nothing", func(t *testing.T) {
			require.NoError(t, err, "danmuji:732: given code that needs no extra imports > then injects nothing | expect (expect err == nil)")
			assert.False(t, strings.Contains(goCode, "import"), "danmuji:733: given code that needs no extra imports > then injects nothing | reject (reject strings.Contains(goCode, \"import\"))")
		})
	})
}

// =============================================================================
// COMPOSITION: Multiple features together
// =============================================================================

func TestTranspileComposition(t *testing.T) {
	t.Run("let + fstring + guard together", func(t *testing.T) {
		source := []byte("package main\nimport \"fmt\"\nfunc greet(name string) string {\n\tguard name != \"\" else {\n\t\treturn \"anonymous\"\n\t}\n\tlet greeting = f\"hello {name}\"\n\treturn greeting\n}\nfunc main() { fmt.Println(greet(\"alice\")) }\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:748: given let + fstring + guard together > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("all features are present", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "if !(name != \"\")"), "danmuji:751: given let + fstring + guard together > then all features are present | expect (expect strings.Contains(goCode, \"if !(name != \\\"\\\")\"))")
			assert.True(t, strings.Contains(goCode, "greeting := fmt.Sprintf"), "danmuji:752: given let + fstring + guard together > then all features are present | expect (expect strings.Contains(goCode, \"greeting := fmt.Sprintf\"))")
		})
		t.Run("no fw keywords remain", func(t *testing.T) {
			assert.False(t, strings.Contains(goCode, "guard "), "danmuji:755: given let + fstring + guard together > then no fw keywords remain | reject (reject strings.Contains(goCode, \"guard \"))")
			assert.False(t, strings.Contains(goCode, "let "), "danmuji:756: given let + fstring + guard together > then no fw keywords remain | reject (reject strings.Contains(goCode, \"let \"))")
		})
	})
	t.Run("enum + impl + derive together", func(t *testing.T) {
		source := []byte("package main\ntype Vec2 struct {\n\tX float64\n\tY float64\n}\nderive Equal for Vec2\nimpl Vec2 {\n\tfunc Add(other Vec2) Vec2 {\n\t\treturn Vec2{X: self.X + other.X, Y: self.Y + other.Y}\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:765: given enum + impl + derive together > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("generates both Equal and methods", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "func (x Vec2) Equal(other Vec2) bool"), "danmuji:768: given enum + impl + derive together > then generates both Equal and methods | expect (expect strings.Contains(goCode, \"func (x Vec2) Equal(other Vec2) bool\"))")
			assert.True(t, strings.Contains(goCode, "func (self Vec2)"), "danmuji:769: given enum + impl + derive together > then generates both Equal and methods | expect (expect strings.Contains(goCode, \"func (self Vec2)\"))")
		})
	})
	t.Run("pipeline + for_in + fstring together", func(t *testing.T) {
		source := []byte("package main\nimport \"fmt\"\nimport \"strings\"\nfunc main() {\n\tnames := []string{\"alice\", \"bob\"}\n\tfor name in names {\n\t\tresult := name |> strings.ToUpper\n\t\tmsg := f\"user: {result}\"\n\t\tfmt.Println(msg)\n\t}\n}\n")
		goCode, err := ferrouswheel.Transpile(source)

		t.Run("transpiles without error", func(t *testing.T) {
			require.NoError(t, err, "danmuji:778: given pipeline + for_in + fstring together > then transpiles without error | expect (expect err == nil)")
		})
		t.Run("pipeline becomes function call", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "strings.ToUpper(name)"), "danmuji:781: given pipeline + for_in + fstring together > then pipeline becomes function call | expect (expect strings.Contains(goCode, \"strings.ToUpper(name)\"))")
		})
		t.Run("for-in becomes range", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "for _, name := range names"), "danmuji:784: given pipeline + for_in + fstring together > then for-in becomes range | expect (expect strings.Contains(goCode, \"for _, name := range names\"))")
		})
		t.Run("fstring becomes Sprintf", func(t *testing.T) {
			assert.True(t, strings.Contains(goCode, "fmt.Sprintf"), "danmuji:787: given pipeline + for_in + fstring together > then fstring becomes Sprintf | expect (expect strings.Contains(goCode, \"fmt.Sprintf\"))")
		})
	})
}

// =============================================================================
// BENCHMARKS
// =============================================================================

func BenchmarkTranspileSimpleLet(b *testing.B) {
	source := []byte("package main\nfunc f() {\n\tlet x = 42\n\t_ = x\n}\n")
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		ferrouswheel.Transpile(source)
	}
}

func BenchmarkTranspileComplexProgram(b *testing.B) {
	source := []byte("package main\nimport \"fmt\"\nenum Color {\n\tRed,\n\tGreen,\n\tBlue(int),\n}\nderive Equal for Color\nimpl Color {\n\tfunc Tag() int {\n\t\treturn self.tag\n\t}\n}\nfunc main() {\n\tlet c = Red()\n\tfor i in 0 .. 10 {\n\t\tfmt.Println(f\"color tag: {c.Tag()}\")\n\t\t_ = i\n\t}\n}\n")
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		ferrouswheel.Transpile(source)
	}
}
