// Package main implements the ferrous-wheel CLI tool.
//
// Commands:
//
//	ferrous-wheel run  <file.fw>           — transpile and execute immediately
//	ferrous-wheel build <file.fw> [-o out] — transpile and compile to a native binary
//	ferrous-wheel emit <file.fw>           — print generated Go to stdout
//	ferrous-wheel fmt  [--check|-w] <file.fw>... — format .fw source files
package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	ferrouswheel "github.com/odvcencio/ferrous-wheel"
)

const generatedHeader = "// Code generated by ferrous-wheel — DO NOT EDIT.\n\n"

const (
	usageMain  = "Usage: ferrous-wheel <command> <file.fw>\nCommands: run, build, emit, lsp, fmt, lint\n"
	usageRun   = "Usage: ferrous-wheel run <file.fw>\n"
	usageBuild = "Usage: ferrous-wheel build <file.fw> [-o output]\n"
	usageEmit  = "Usage: ferrous-wheel emit <file.fw>\n"
	usageFmt   = "Usage: ferrous-wheel fmt [--check|-w] <file.fw>...\n"
	usageLint  = "Usage: ferrous-wheel lint <file.fw>...\n"
)

type cliUsageError string

func (e cliUsageError) Error() string {
	return string(e)
}

func main() {
	os.Exit(runCLI(os.Args, os.Stderr))
}

func runCLI(args []string, stderr io.Writer) int {
	if len(args) < 2 {
		fmt.Fprint(stderr, usageMain)
		return 1
	}

	switch args[1] {
	case "run":
		path, err := singlePathArg(args[2:], usageRun)
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := run(path); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "build":
		path, output, err := buildArgs(args[2:])
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := build(path, output); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "emit":
		path, err := singlePathArg(args[2:], usageEmit)
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := emit(path); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "lsp":
		return runLSP()
	case "fmt":
		return runFmt(args[2:], stderr)
	case "lint":
		return runLint(args[2:], stderr)
	default:
		fmt.Fprintf(stderr, "Unknown command: %s\n%s", args[1], usageMain)
		return 1
	}
	return 0
}

func singlePathArg(args []string, usage string) (string, error) {
	if len(args) != 1 {
		return "", cliUsageError(usage)
	}
	return args[0], nil
}

func buildArgs(args []string) (string, string, error) {
	if len(args) == 0 {
		return "", "", cliUsageError(usageBuild)
	}
	if args[0] == "-o" {
		return "", "", cliUsageError(usageBuild)
	}

	path := args[0]
	output := ""
	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "-o":
			if output != "" {
				return "", "", cliUsageError("duplicate -o flag\n" + usageBuild)
			}
			if i+1 >= len(args) || args[i+1] == "" {
				return "", "", cliUsageError("missing output path after -o\n" + usageBuild)
			}
			output = args[i+1]
			i++
		default:
			return "", "", cliUsageError(fmt.Sprintf("unexpected build argument: %s\n%s", args[i], usageBuild))
		}
	}

	return path, output, nil
}

// transpileFile reads a .fw file and returns the generated Go source.
// Lint runs automatically before transpilation. LintError diagnostics block
// transpilation; warnings and info are printed to stderr but don't block.
func transpileFile(path string) (string, []ferrouswheel.Warning, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", nil, fmt.Errorf("read %s: %w", path, err)
	}

	// Run lint before transpilation
	if lintFile(path, source, os.Stderr) {
		return "", nil, fmt.Errorf("lint errors found in %s", path)
	}

	goCode, warnings, err := ferrouswheel.TranspileWithOptions(source, ferrouswheel.TranspileOptions{
		SourceFile: path,
		LintRan:    true,
	})
	if err != nil {
		return "", nil, fmt.Errorf("transpile %s: %w", path, err)
	}
	return generatedHeader + goCode, warnings, nil
}

func printWarnings(w io.Writer, warnings []ferrouswheel.Warning) {
	for _, warning := range warnings {
		if warning.Line > 0 {
			fmt.Fprintf(w, "warning: line %d:%d: %s\n", warning.Line, warning.Col, warning.Message)
			continue
		}
		fmt.Fprintf(w, "warning: %s\n", warning.Message)
	}
}

// findParentGoMod walks up from start looking for a directory that contains
// a go.mod file. Returns the directory path or "" if none found before the
// filesystem root.
func findParentGoMod(start string) string {
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// writeTempProject writes Go source + (optionally) a go.mod to a temp
// directory and returns the path.
//
// If sourcePath is non-empty and lives inside a Go module, the temp project
// is staged as `<module-root>/.ferrous-wheel-build/fwrun-*/main.go`. No
// go.mod is written — Go's module discovery walks up and inherits the
// parent module's go.mod, including all of its dependencies and replace
// directives. This lets .fw scripts use any third-party package that the
// host project already depends on.
//
// If sourcePath is empty or no parent go.mod is found, falls back to
// writing a self-contained temp project under /tmp with a fresh
// `module fwrun` go.mod (stdlib-only).
//
// Go's `./...` walker skips dot-prefixed directories, so the staging
// directory does not pollute project-wide builds.
func writeTempProject(goCode, sourcePath string) (string, func(), error) {
	if sourcePath != "" {
		if absSource, err := filepath.Abs(sourcePath); err == nil {
			if parentMod := findParentGoMod(filepath.Dir(absSource)); parentMod != "" {
				stageRoot := filepath.Join(parentMod, ".ferrous-wheel-build")
				if mkErr := os.MkdirAll(stageRoot, 0755); mkErr != nil {
					return "", nil, fmt.Errorf("create stage root: %w", mkErr)
				}
				tmpDir, err := os.MkdirTemp(stageRoot, "fwrun-*")
				if err != nil {
					return "", nil, fmt.Errorf("create temp dir: %w", err)
				}
				cleanup := func() { os.RemoveAll(tmpDir) }
				if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(goCode), 0644); err != nil {
					cleanup()
					return "", nil, fmt.Errorf("write main.go: %w", err)
				}
				return tmpDir, cleanup, nil
			}
		}
	}

	tmpDir, err := os.MkdirTemp("", "ferrous-wheel-*")
	if err != nil {
		return "", nil, fmt.Errorf("create temp dir: %w", err)
	}
	cleanup := func() { os.RemoveAll(tmpDir) }

	goMod := "module fwrun\n\ngo 1.24.0\n"
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("write go.mod: %w", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(goCode), 0644); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("write main.go: %w", err)
	}
	return tmpDir, cleanup, nil
}

// run transpiles a .fw file and executes it immediately.
func run(path string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)

	tmpDir, cleanup, err := writeTempProject(goCode, path)
	if err != nil {
		return err
	}
	defer cleanup()

	cmd := exec.Command("go", "run", ".")
	cmd.Dir = tmpDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go run: %w", err)
	}
	return nil
}

// build transpiles a .fw file and compiles it to a native binary.
func build(path, output string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)

	tmpDir, cleanup, err := writeTempProject(goCode, path)
	if err != nil {
		return err
	}
	defer cleanup()

	// Determine output binary name
	if output == "" {
		output = strings.TrimSuffix(filepath.Base(path), ".fw")
	}
	// Make output path absolute relative to cwd
	if !filepath.IsAbs(output) {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getwd: %w", err)
		}
		output = filepath.Join(cwd, output)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	cmd := exec.Command("go", "build", "-o", output, ".")
	cmd.Dir = tmpDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go build: %w", err)
	}

	fmt.Fprintf(os.Stderr, "  %s -> %s\n", filepath.Base(path), filepath.Base(output))
	return nil
}

// emit transpiles a .fw file and prints the generated Go to stdout.
func emit(path string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)
	fmt.Print(goCode)
	return nil
}

// runFmt implements the fmt subcommand.
// Flags:
//
//	--check: exit 1 if any file would be changed (for CI)
//	-w:      write formatted output back to file(s) in place
//
// With no flags, formatted output is printed to stdout.
// When -w is used with a directory argument, all .fw files are formatted recursively.
func runFmt(args []string, stderr io.Writer) int {
	check := false
	write := false
	var paths []string

	for _, arg := range args {
		switch arg {
		case "--check":
			check = true
		case "-w":
			write = true
		default:
			paths = append(paths, arg)
		}
	}

	if len(paths) == 0 {
		fmt.Fprint(stderr, usageFmt)
		return 1
	}

	// Expand directories to .fw files recursively.
	var files []string
	for _, p := range paths {
		info, err := os.Stat(p)
		if err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
		if info.IsDir() {
			err := filepath.WalkDir(p, func(path string, d os.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if !d.IsDir() && strings.HasSuffix(path, ".fw") {
					files = append(files, path)
				}
				return nil
			})
			if err != nil {
				fmt.Fprintf(stderr, "error: %v\n", err)
				return 1
			}
		} else {
			files = append(files, p)
		}
	}

	exitCode := 0
	for _, path := range files {
		source, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(stderr, "error: read %s: %v\n", path, err)
			return 1
		}

		formatted, err := ferrouswheel.Format(source)
		if err != nil {
			fmt.Fprintf(stderr, "error: format %s: %v\n", path, err)
			return 1
		}

		switch {
		case check:
			if !bytes.Equal(source, formatted) {
				fmt.Fprintf(stderr, "%s: not formatted\n", path)
				exitCode = 1
			}
		case write:
			if !bytes.Equal(source, formatted) {
				if err := os.WriteFile(path, formatted, 0644); err != nil {
					fmt.Fprintf(stderr, "error: write %s: %v\n", path, err)
					return 1
				}
			}
		default:
			os.Stdout.Write(formatted)
		}
	}

	return exitCode
}

// runLint implements the lint subcommand.
func runLint(args []string, stderr io.Writer) int {
	if len(args) == 0 {
		fmt.Fprint(stderr, usageLint)
		return 1
	}

	hasError := false
	for _, path := range args {
		source, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
		diags, err := ferrouswheel.Lint(source)
		if err != nil {
			fmt.Fprintf(stderr, "error: lint %s: %v\n", path, err)
			return 1
		}
		for _, d := range diags {
			fmt.Fprintf(stderr, "%s:%d:%d: [%s] %s: %s\n",
				path, d.Line, d.Col, d.Severity, d.Rule, d.Message)
			if d.Severity == ferrouswheel.LintError {
				hasError = true
			}
		}
	}
	if hasError {
		return 1
	}
	return 0
}

// lintFile runs lint on a source file and prints diagnostics. Returns true if
// any LintError diagnostics were found (which should block transpilation).
func lintFile(path string, source []byte, stderr io.Writer) bool {
	diags, err := ferrouswheel.Lint(source)
	if err != nil {
		// Lint errors are non-fatal for the pipeline; just warn.
		fmt.Fprintf(stderr, "lint: %s: %v\n", path, err)
		return false
	}
	hasError := false
	for _, d := range diags {
		fmt.Fprintf(stderr, "%s:%d:%d: [%s] %s: %s\n",
			path, d.Line, d.Col, d.Severity, d.Rule, d.Message)
		if d.Severity == ferrouswheel.LintError {
			hasError = true
		}
	}
	return hasError
}
