// Package main implements the ferrous-wheel CLI tool.
//
// Commands:
//
//	ferrous-wheel run  <file.fw>           — transpile and execute immediately
//	ferrous-wheel build <file.fw> [-o out] — transpile and compile to a native binary
//	ferrous-wheel emit <file.fw>           — print generated Go to stdout
package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	ferrouswheel "github.com/odvcencio/ferrous-wheel"
)

const generatedHeader = "// Code generated by ferrous-wheel — DO NOT EDIT.\n\n"

const (
	usageMain  = "Usage: ferrous-wheel <command> <file.fw>\nCommands: run, build, emit, lsp\n"
	usageRun   = "Usage: ferrous-wheel run <file.fw>\n"
	usageBuild = "Usage: ferrous-wheel build <file.fw> [-o output]\n"
	usageEmit  = "Usage: ferrous-wheel emit <file.fw>\n"
)

type cliUsageError string

func (e cliUsageError) Error() string {
	return string(e)
}

func main() {
	os.Exit(runCLI(os.Args, os.Stderr))
}

func runCLI(args []string, stderr io.Writer) int {
	if len(args) < 2 {
		fmt.Fprint(stderr, usageMain)
		return 1
	}

	switch args[1] {
	case "run":
		path, err := singlePathArg(args[2:], usageRun)
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := run(path); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "build":
		path, output, err := buildArgs(args[2:])
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := build(path, output); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "emit":
		path, err := singlePathArg(args[2:], usageEmit)
		if err != nil {
			fmt.Fprint(stderr, err)
			return 1
		}
		if err := emit(path); err != nil {
			fmt.Fprintf(stderr, "error: %v\n", err)
			return 1
		}
	case "lsp":
		return runLSP()
	default:
		fmt.Fprintf(stderr, "Unknown command: %s\n%s", args[1], usageMain)
		return 1
	}
	return 0
}

func singlePathArg(args []string, usage string) (string, error) {
	if len(args) != 1 {
		return "", cliUsageError(usage)
	}
	return args[0], nil
}

func buildArgs(args []string) (string, string, error) {
	if len(args) == 0 {
		return "", "", cliUsageError(usageBuild)
	}
	if args[0] == "-o" {
		return "", "", cliUsageError(usageBuild)
	}

	path := args[0]
	output := ""
	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "-o":
			if output != "" {
				return "", "", cliUsageError("duplicate -o flag\n" + usageBuild)
			}
			if i+1 >= len(args) || args[i+1] == "" {
				return "", "", cliUsageError("missing output path after -o\n" + usageBuild)
			}
			output = args[i+1]
			i++
		default:
			return "", "", cliUsageError(fmt.Sprintf("unexpected build argument: %s\n%s", args[i], usageBuild))
		}
	}

	return path, output, nil
}

// transpileFile reads a .fw file and returns the generated Go source.
func transpileFile(path string) (string, []ferrouswheel.Warning, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", nil, fmt.Errorf("read %s: %w", path, err)
	}
	goCode, warnings, err := ferrouswheel.TranspileWithOptions(source, ferrouswheel.TranspileOptions{
		SourceFile: path,
	})
	if err != nil {
		return "", nil, fmt.Errorf("transpile %s: %w", path, err)
	}
	return generatedHeader + goCode, warnings, nil
}

func printWarnings(w io.Writer, warnings []ferrouswheel.Warning) {
	for _, warning := range warnings {
		if warning.Line > 0 {
			fmt.Fprintf(w, "warning: line %d:%d: %s\n", warning.Line, warning.Col, warning.Message)
			continue
		}
		fmt.Fprintf(w, "warning: %s\n", warning.Message)
	}
}

// writeTempProject writes Go source + go.mod to a temp directory and returns the path.
func writeTempProject(goCode string) (string, func(), error) {
	tmpDir, err := os.MkdirTemp("", "ferrous-wheel-*")
	if err != nil {
		return "", nil, fmt.Errorf("create temp dir: %w", err)
	}
	cleanup := func() { os.RemoveAll(tmpDir) }

	goMod := "module fwrun\n\ngo 1.24.0\n"
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("write go.mod: %w", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(goCode), 0644); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("write main.go: %w", err)
	}
	return tmpDir, cleanup, nil
}

// run transpiles a .fw file and executes it immediately.
func run(path string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)

	tmpDir, cleanup, err := writeTempProject(goCode)
	if err != nil {
		return err
	}
	defer cleanup()

	cmd := exec.Command("go", "run", ".")
	cmd.Dir = tmpDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go run: %w", err)
	}
	return nil
}

// build transpiles a .fw file and compiles it to a native binary.
func build(path, output string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)

	tmpDir, cleanup, err := writeTempProject(goCode)
	if err != nil {
		return err
	}
	defer cleanup()

	// Determine output binary name
	if output == "" {
		output = strings.TrimSuffix(filepath.Base(path), ".fw")
	}
	// Make output path absolute relative to cwd
	if !filepath.IsAbs(output) {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getwd: %w", err)
		}
		output = filepath.Join(cwd, output)
	}
	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	cmd := exec.Command("go", "build", "-o", output, ".")
	cmd.Dir = tmpDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go build: %w", err)
	}

	fmt.Fprintf(os.Stderr, "  %s -> %s\n", filepath.Base(path), filepath.Base(output))
	return nil
}

// emit transpiles a .fw file and prints the generated Go to stdout.
func emit(path string) error {
	goCode, warnings, err := transpileFile(path)
	if err != nil {
		return err
	}
	printWarnings(os.Stderr, warnings)
	fmt.Print(goCode)
	return nil
}
