// Package main implements the ferrous-wheel CLI tool that transpiles .fw files
// to _generated.go files containing standard Go code.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	ferrouswheel "github.com/odvcencio/ferrous-wheel"
)

const generatedHeader = "// Code generated by ferrous-wheel — DO NOT EDIT.\n\n"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: ferrous-wheel build <path>\n")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "build":
		if len(os.Args) < 3 {
			fmt.Fprintf(os.Stderr, "Usage: ferrous-wheel build <path>\n")
			os.Exit(1)
		}
		if err := build(os.Args[2]); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\nUsage: ferrous-wheel build <path>\n", os.Args[1])
		os.Exit(1)
	}
}

func build(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	if info.IsDir() {
		return buildDir(path)
	}
	return buildFile(path)
}

func buildDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	count := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".fw") {
			continue
		}
		if err := buildFile(filepath.Join(dir, entry.Name())); err != nil {
			return err
		}
		count++
	}
	fmt.Printf("ferrous-wheel: transpiled %d file(s)\n", count)
	return nil
}

func buildFile(path string) error {
	source, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	goCode, err := ferrouswheel.Transpile(source)
	if err != nil {
		return fmt.Errorf("transpile %s: %w", path, err)
	}

	// Output: foo.fw -> foo_generated.go
	base := strings.TrimSuffix(filepath.Base(path), ".fw")
	outName := base + "_generated.go"
	outPath := filepath.Join(filepath.Dir(path), outName)

	output := generatedHeader + goCode
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	fmt.Printf("  %s -> %s\n", filepath.Base(path), outName)
	return nil
}
